# Generated by Django 4.2.1 on 2023-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.FileField(upload_to='', verbose_name='用户头像')),
                ('photo_url', models.CharField(default='', max_length=128, verbose_name='用户头像路径')),
                ('bio', models.CharField(default='', max_length=256, verbose_name='个人简介')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
